import {
  CINATRA_NANGO_PROVIDER_CONFIG_KEYS,
  type NangoConnectorKey,
} from "./nango";

export type NangoConnectorDefinition = {
  key: NangoConnectorKey;
  title: string;
  description: string;
  providerConfigKey: string;
  connectDisplayName?: string;
  multiple?: boolean;
  manageHref?: string;
  usesConnectUI: boolean;
};

export const NANGO_CONNECTOR_DEFINITIONS: Record<NangoConnectorKey, NangoConnectorDefinition> = {
  // Generic A2A server connector. `multiple: true` supports one
  // saved Nango record per peer server (user-provided baseUrl stored in
  // metadata.baseUrl). `usesConnectUI: false` because API-key-style peers are
  // wired via importNangoConnection server-side rather than the Connect UI.
  a2aServer: {
    key: "a2aServer",
    title: "A2A Server",
    connectDisplayName: "A2A Server",
    description: "Connect an external A2A (Agent-to-Agent) server. Stores the server's base URL + bearer token; fresh credentials are fetched every dispatch.",
    providerConfigKey: CINATRA_NANGO_PROVIDER_CONFIG_KEYS.a2aServer,
    multiple: true,
    usesConnectUI: false,
  },
  // Apify is a first-party connector with a single API token
  // per workspace. `multiple: false`, `usesConnectUI: false` because the
  // token is collected by the cinatra-native settings page at
  // /connectors/apify and saved via importNangoConnection server-side.
  // The MCP tool builder lives at src/lib/apify-mcp-connection.ts.
  apify: {
    key: "apify",
    title: "Apify",
    description: "Apify API token — registers the Apify MCP server with every LLM call.",
    providerConfigKey: CINATRA_NANGO_PROVIDER_CONFIG_KEYS.apify,
    manageHref: "/connectors/apify",
    usesConnectUI: false,
  },
  apollo: {
    key: "apollo",
    title: "Apollo API",
    description: "Configure the app-level Apollo connection used for Ross Index enrichment.",
    providerConfigKey: CINATRA_NANGO_PROVIDER_CONFIG_KEYS.apollo,
    usesConnectUI: true,
  },
  claude: {
    key: "claude",
    title: "Anthropic API",
    description: "Configure the app-level Anthropic connection for Claude-powered workflows.",
    providerConfigKey: CINATRA_NANGO_PROVIDER_CONFIG_KEYS.claude,
    usesConnectUI: true,
  },
  // Drupal is a first-party multi-tenant connector. Per-instance
  // Bearer tokens generated by `drush mcp-tools:remote-key-create` on each
  // customer's Drupal site. `multiple: true`, `usesConnectUI: false` because
  // the token + site URL are collected by /connectors/drupal and saved via
  // importNangoConnection server-side. The MCP tool builder lives at
  // src/lib/drupal-mcp-connection.ts.
  drupal: {
    key: "drupal",
    title: "Drupal",
    description: "Per-site Drupal mcp_tools Bearer token. Each site is its own connection.",
    providerConfigKey: CINATRA_NANGO_PROVIDER_CONFIG_KEYS.drupal,
    multiple: true,
    manageHref: "/connectors/drupal",
    usesConnectUI: false,
  },
  github: {
    key: "github",
    title: "GitHub API",
    connectDisplayName: "GitHub",
    description: "Connect the GitHub account Cinatra should use to access repositories and manage skill package files.",
    providerConfigKey: CINATRA_NANGO_PROVIDER_CONFIG_KEYS.github,
    manageHref: "/configuration/llm/github",
    usesConnectUI: true,
  },
  gmail: {
    key: "gmail",
    title: "Gmail",
    description: "Connect your Gmail account.",
    providerConfigKey: CINATRA_NANGO_PROVIDER_CONFIG_KEYS.gmail,
    usesConnectUI: true,
  },
  // The Gemini API key is collected by an in-page modal at
  // /configuration/llm?modal=gemini and
  // saved via syncGeminiAPISettingsToNango (readback-safe pattern).
  // The Nango Connect UI is no longer used for Gemini.
  gemini: {
    key: "gemini",
    title: "Gemini API",
    description: "Configure the app-level Gemini connection used for transcript and image workflows.",
    providerConfigKey: CINATRA_NANGO_PROVIDER_CONFIG_KEYS.gemini,
    manageHref: "/configuration/llm?modal=gemini",
    usesConnectUI: false,
  },
  googleCalendar: {
    key: "googleCalendar",
    title: "Google Calendar",
    description: "Connect your Google Calendar account.",
    providerConfigKey: CINATRA_NANGO_PROVIDER_CONFIG_KEYS.googleCalendar,
    usesConnectUI: true,
  },
  googleOAuth: {
    key: "googleOAuth",
    title: "Google OAuth",
    description: "Configure the app-level Google OAuth administration used for Gmail, Google Calendar, and Google sign-in.",
    providerConfigKey: CINATRA_NANGO_PROVIDER_CONFIG_KEYS.googleOAuth,
    // Stable settings URL; /configuration/llm/gmail redirects to the
    // google-oauth-connector dispatch route. The former
    // ?modal=gmail value was inert (no modal renderer on the LLM page).
    manageHref: "/configuration/llm/gmail",
    usesConnectUI: true,
  },
  linkedin: {
    key: "linkedin",
    title: "LinkedIn API",
    connectDisplayName: "LinkedIn",
    description: "Configure the LinkedIn OAuth app and manage the LinkedIn accounts available for content syndication.",
    providerConfigKey: CINATRA_NANGO_PROVIDER_CONFIG_KEYS.linkedin,
    multiple: true,
    manageHref: "/configuration/llm?modal=linkedin",
    usesConnectUI: true,
  },
  openai: {
    key: "openai",
    title: "OpenAI API",
    description: "Configure the app-level OpenAI connection for Cinatra’s model-backed workflows.",
    providerConfigKey: CINATRA_NANGO_PROVIDER_CONFIG_KEYS.openai,
    manageHref: "/configuration/llm?modal=openai",
    usesConnectUI: true,
  },
  // Tailscale OAuth client for auto-tunneling clones.
  // `usesConnectUI: false` — Cinatra provides its own paste form at
  // `/connectors/tailscale` (matches the API-key connector convention; the
  // Nango Connect UI is not invoked). The dev tab links here.
  tailscale: {
    key: "tailscale",
    title: "Tailscale (auto-tunnel)",
    description: "OAuth client used to mint per-clone Tailscale Funnel auth-keys automatically.",
    providerConfigKey: CINATRA_NANGO_PROVIDER_CONFIG_KEYS.tailscale,
    manageHref: "/connectors/tailscale",
    usesConnectUI: false,
  },
  wordpress: {
    key: "wordpress",
    title: "WordPress API",
    description: "Manage app-level self-hosted WordPress publishing connections per site.",
    providerConfigKey: CINATRA_NANGO_PROVIDER_CONFIG_KEYS.wordpress,
    multiple: true,
    manageHref: "/configuration/llm?modal=wordpress",
    usesConnectUI: true,
  },
  youtube: {
    key: "youtube",
    title: "YouTube API",
    connectDisplayName: "YouTube",
    description: "Connect the organization YouTube account Cinatra should use for transcript discovery.",
    providerConfigKey: CINATRA_NANGO_PROVIDER_CONFIG_KEYS.youtube,
    manageHref: "/configuration/llm/youtube",
    usesConnectUI: true,
  },
};
